### ISSUE TITLE
Use JSON schemas to validate JSON input/output

### ISSUE THREAD

**Issue by serin-delaunay** [Wangscape/Wangscape#21]
~At the moment only basic tests are performed on JSON input/output. There is a schema for the options file which is kept updated, but I haven't found any libraries with permissive licenses that are able to run the validation without crashing. I've tried versions of picojson, rapidjson, and valijson, but I don't remember exactly which versions - it may have been an outdated version of rapidjson (see #20).~

~Python and JS have mature, functioning tools for this purpose - one option may be to run JSON validation in an external process.~

* ~Integrate a working JSON schema validator with the codebase.~
* ~Define appropriate schemas for the output JSON files.~
* ~Use the schemas to validate I/O JSON files in tests (and possibly in the main program).~

Now that spotify-json is used for JSON I/O in Wangscape and WangscapeTest, the issue is somewhat different. JSON schemas should be available for all the I/O formats. They will serve as:
* A formal specification of the formats, for people who want to work with them manually or write applications using them.
* A validation tool for use outside of the C++ Wangscape/WangscapeTest executables (in particular in Wangview).

TODO:
- [x] Schemas for configuration formats (done in https://github.com/serin-delaunay/Wangscape/tree/top-left-border-modules/).
- [x] Schemas for metaoutput formats (#114, https://github.com/Wangscape/Wangcheck/pull/2)
- [x] Host an updated docson somewhere ([github.io](https://wangscape.github.io/docson)) so the schemas can be pretty-printed and referred to easily.
- [x] Link to the docson-formatted schemas in the Wangscape documentation (Done in #104 ).
* ~Fix module schema display, if possible.~ Apparently it's not.
- [x] Write a Python tool to validate configuration and output using schemas (#112, https://github.com/Wangscape/Wangcheck/pull/1).

**Comment by hryniuk** [comment]
I've got a good experience with [spotify-json](https://github.com/spotify/spotify-json), you can use it for validating, serializing and deserializing JSONs. It can be added as submodule (IMO that's the best way to add a library to your project).

I can do it as well and then you will have more time to spend on algorithm implementation and different tile types handling.

**Comment by serin-delaunay** [comment]
Spotify-json looks suitable for the job. It looks like validation is done by static analysis of the target class rather than with JSON schemas? That might make manual editing of options files more difficult, but manual JSON editing is not meant to be a long-term solution for Wangscape configuration. And the API looks nicer than rapidjson's. 

Feel free to implement this :)

**Comment by hryniuk** [comment]
Yes, that's right - defined class determines how JSON should look like and you set selected fields as optional in decoder to have two ways conversion.

With **spotify-json** there will be not lines like this:
```cpp
TerrainSpec(
    v.FindMember("FullName")->value.GetString(),
    v.FindMember("FileName")->value.GetString(),
    v.FindMember("OffsetX")->value.GetInt(),
    v.FindMember("OffsetY")->value.GetInt())
```

It's just `TerrainSpec` parsing.

Mmm... we should ask ourselves how many fields from configuraton JSON are really necessary. I've started implementing **logger** with including `boost::program_options` and I think e.g. `OutputDirectory` could be passed from the command line (it will require that Wangscape's users run it in a console :confused:).

On the other hand, command line arguments could overwrite JSON config and user could just do something like that:
```shell
./Wangscape --config-file options.json --tile-format 16 --filetype jpg
```
and then Wangscape will use these two options and read the rest from the file. After tileset generation, it will save passed `tile-format` and `filetype` to `options.json` (saving some backup file maybe).

For now, as far as I saw, it's not possible to run Wangscape without config file. It will be nice to have some default options and read as much as possible from input files. E.g.:
```shell
./Wangscape tile1.png tile2.png
```
could deduce tile sizes, use common filetype, generate tileset in `output` directory by default and read `FullName`, `FileName` from passed arguments. MetaOutput options could be default in source code as well.

How do you feel about that?

**Comment by serin-delaunay** [comment]
I agree that most of what is currently in the options file can be made implicit or overridable in the command line. There shouldn't be any problem running the program without an options file, for simple configurations like:
```
./Wangscape tile1.png tile2.png
```
It should of course fail if tile1 and tile2 don't have the correct size, or `--tile-format` is specified and one of the tiles is too small. MetaOutput filenames can all have default options, `resolution` can be guessed, `FileType` can be `png`, `offsetX` and `offsetY` can be 0 by default, terrain ids could be derived from filenames. However, there are some limitations:
* This would be inadvisable with 6 or more input terrains, and bad with 12 or more, because the output tileset dimensions risk exceeding the maximum texture size of a low-end graphics card. This is what the clique specifications are for, and I for one would not enjoy writing clique specifications on the command line ;) Automatically selecting cliques would probably not be practical.
* Once #15 is implemented, each terrain and each pair of terrains that share a clique will have a noise module associated with it. Except for very basic options, these would probably have to be guessed (and the guesses may be quite unsatisfying).

I think it would be good to allow simple command line options, but automatically generate an `options.json` in the output folder so that the user can alter the generation parameters in more detail, without having to write the file from scratch. There could be a `--generate-options` flag that writes the options, and a `--dont-generate` flag that prevents Wangscape from generating tiles.

**Comment by hryniuk** [comment]
Options generation is what I thought about when you wrote:

> manual JSON editing is not meant to be a long-term solution for Wangscape configuration

I'll think of it and I'll try to choose the _proper_ set of command line options.

> It should of course fail if tile1 and tile2 don't have the correct size

Yeah, but it could also analyze input tiles, generate as much configuration (with comments maybe) as it's possible for these tiles and print some tips about filling the rest. I'm not sure if it's a proper way to handle a wrong input, but we can always try and see how it works.

**Comment by serin-delaunay** [comment]
> > It should of course fail if tile1 and tile2 don't have the correct size
>
> Yeah, but it could also analyze input tiles, generate as much configuration (with comments maybe) as it's possible for these tiles and print some tips about filling the rest.

Sorry, I meant to write "if [they] don't have the same size". Though if one image is a multiple of the other's size, it can be treated as a set of terrains. In theory this could be used to specify cliques on the command line, but that would require identifying all the duplicate tiles in the inputs.

**Comment by hryniuk** [comment]
Good news: Wangscape already builds and works correctly (on provided examples) without RapidJSON using `spotify-json` instead 😀. I only need to fix (or remove) tests that included the former.

If you'd like to take a look, go to my **spotify-json** branch: https://github.com/hryniuk/Wangscape/tree/spotify-json. There will be (finally) a **PR** of course, as soon as I'll finish.

**Comment by hryniuk** [comment]
What's the status of this issue? Does Wangscape still need JSON schema validation? Options/output can be validated with the structs and codec from `spotify-json`.

I think that JSON schemas could be useful as it would be much harder to store all information in e.g. comments around the code, but that's only the second point:
>Define appropriate schemas for the output JSON files.

**Comment by serin-delaunay** [comment]
I think spotify-json has resolved this issue for the C++ Wangscape executable and tests, but the project as a whole still needs JSON schemas for:
* Wangview
* Documentation/specification of JSON formats for:
  * People who want to manually write options files.
  * People who want to write applications using output from Wangscape.

I don't think spotify-json codecs, or even well-commented spotify-json codecs, will be suitable as documentation. Doxygen output from codec classes might work, if well-configured.

**Comment by hryniuk** [comment]
If you have Doxygen comments in mind, they would only clutter codecs' code in my opinion... but I'll accept your decision of course :wink:. For me **up-to-date** JSON schemas are the best option.

Why do we need schemas for Wangview? Aren't schemas of Wangscape output enough?

**Comment by serin-delaunay** [comment]
You're right, Doxygen files from codec classes are probably not the right way to go. I do think the formats should be documented not just in JSON schemas, but also in a more human-readable format like HTML. There are several tools for converting JSON schemas to HTML documentation:

* https://github.com/mattyod/matic
* https://github.com/cloudflare/json-schema-docs-generator
* https://github.com/lbovet/docson
* https://github.com/interagent/prmd

I'll look at them in more detail tomorrow. They all seem to depend on node.js. I don't think that's a problem for a documentation generator.

Wangview won't need any schemas of its own - it can use the Wangscape metaoutput schemas. But we don't have any schemas for the metaoutput yet, so Wangview needs them! ;)

**Comment by hryniuk** [comment]
Now everything's clear :). I'll take a look at them too...

I've just got an idea of importing them somewhat into Markdown files and then generate HTML documentation with one of static page generators. With GitHub Pages we could probably get anything we need.

**Comment by serin-delaunay** [comment]
Some notes on the documentation generators:

`matic`'s example output looks nice and runs fast on desktop and mobile. It hasn't been significantly updated in 3 years, and it's only tested with `Jade`, which is deprecated in favour of `pug`. The example schema is quite simple, so I don't know how well it would cope with the features used in Wangscape's options schema. Worth a try.

`doca` is extremely heavy. The example output (https://api.cloudflare.com/) looks nice but runs slowly on both desktop and mobile. It takes several minutes to install the necessary `npm` packages and initialise, it insists on using a folder named `documentation`, and that folder grows to at least 73 MB with over 20,000 files. And after all that it failed with an `ELIFECYCLE` error.

`docson`'s output ([link](http://lbovet.github.io/docson/index.html#https://raw.githubusercontent.com/serin-delaunay/Wangscape/alpha-calculator-options/Wangscape/options_schema.json)) runs fast; it looks nice on desktop and OK on mobile. The version at github.io doesn't display the `Terrains` schema correctly. I suspect that's because of the `patternProperties` field. Perhaps the github.io version doesn't yet have the fix for [this issue](https://github.com/lbovet/docson/issues/14)? If an up-to-date install works, this could be a good choice.

I can't test `prmd` because I don't currently have Ruby installed. The only example output I can find is [this](https://github.com/sitepoint/prmd-json-schema/blob/master/schema/authentication-api.md), which is rather unimpressive.

**Comment by serin-delaunay** [comment]
OK, I skipped the npm package and used the instructions [here](https://dzone.com/articles/publishing-json-schema-documentaton-with-docson) to run the patched version of docson. `patternProperties` support is great, and the options schema renders very well. However, the [module schema](https://raw.githubusercontent.com/serin-delaunay/Wangscape/top-left-border-modules/doc/schemas/module_group_schema.json)'s `oneOf` property for module schemas breaks the display:
![module group schema](https://cloud.githubusercontent.com/assets/15715657/23220366/adb0af9c-f919-11e6-838d-8798e0a2fc28.PNG)

I'll check whether using different names for the individual module schemas can fix the problem. Either way, I think docson is the best option for this.

I think it would be worthwhile to write a small Python tool that validates a configuration file and its output. The `jsonschema` package works well with these schemas, so it would be a simple task.

**Comment by serin-delaunay** [comment]
https://github.com/Wangscape/Wangcheck will hold the Python script for automatically validating Wangscape configuration.

**Comment by serin-delaunay** [comment]
https://github.com/lbovet/docson/pull/44 has a solution for the narrow formatting in docson. I've forked docson to https://github.com/Wangscape/docson, merged that change into `master`, and updated the `gh-pages` branch with the fix for `patternProperties` which was already on `master`. Now we can view schemas using links like https://wangscape.github.io/docson/#https://raw.githubusercontent.com/serin-delaunay/Wangscape/metaoutput-schemas/doc/schemas/options_schema.json.

**Comment by serin-delaunay** [comment]
Closed in https://github.com/Wangscape/Wangcheck/pull/2.
